apiVersion: apps/v1
kind: Deployment
metadata:
  name: jio-server-data
  namespace: jiaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jio-server-data
  template:
    metadata:
      labels:
        app: jio-server-data
    spec:
      containers:
        - name: jio-server-data
          image: 541673202749.dkr.ecr.ap-northeast-2.amazonaws.com/jiaa-server-data:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: KAFKA_BROKER
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
