apiVersion: v1
kind: Service
metadata:
  name: jio-server-data
  namespace: jiaa
spec:
  type: ClusterIP
  selector:
    app: jio-server-data
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
