apiVersion: apps/v1
kind: Deployment
metadata:
  name: jio-server-ai
  namespace: jiaa
  labels:
    app: jio-server-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jio-server-ai
  template:
    metadata:
      labels:
        app: jio-server-ai
    spec:
      containers:
        - name: jio-server-ai
          image: 541673202749.dkr.ecr.ap-northeast-2.amazonaws.com/jiaa-server-ai:latest
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 50051
              name: grpc
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: REDIS_HOST
              value: "redis-master.jiaa-system.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: POSTGRES_HOST
              value: "jiaa-db.cveg64k8yuia.ap-northeast-2.rds.amazonaws.com"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "jiaa"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: jiaa-auth-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jiaa-auth-secret
                  key: POSTGRES_PASSWORD
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jiaa-ai-secret
                  key: openai_api_key
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
