apiVersion: v1
kind: Service
metadata:
  name: jio-server-ai
  namespace: jiaa
  labels:
    app: jio-server-ai
spec:
  selector:
    app: jio-server-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
    - protocol: TCP
      port: 50051
      targetPort: 50051
      name: grpc
  type: ClusterIP
