apiVersion: v1
kind: Service
metadata:
  name: jio-auth
  namespace: jiaa
  labels:
    app: jio-auth
spec:
  selector:
    app: jio-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
