apiVersion: v1
kind: Service
metadata:
  name: jio-server-core
  namespace: jiaa
  labels:
    app: jio-server-core
spec:
  selector:
    app: jio-server-core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 50052
      targetPort: 50052
      name: grpc
  type: ClusterIP
